workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - test
    scripts:
      - name: Set up flutter
        script: |
          flutter channel stable
          flutter upgrade
      - name: Get flutter packages
        script: |
          flutter pub get
      - name: Create .env file
        script: |
          echo "OPEN_AI_API_KEY=$OPEN_AI_API_KEY" > .env
      - name: Build unsigned IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa