name: ELOVANDO_App
description: "ELOVANDO - The Love App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  flutter_svg: ^2.0.10+1
  firebase_storage: ^11.7.4
  image_picker: ^1.1.2
  cloud_firestore: ^4.17.2
  envied: ^0.5.4
  flutter_dotenv: ^5.0.0
  dart_openai: ^5.1.0
  permission_handler: ^11.3.1 
  html: ^0.15.4
  flutter_sound: ^9.4.6 
  record: ^4.4.4
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  path: ^1.9.0
  flutter_facebook_auth: ^7.0.0
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.4
  provider: ^6.1.2
  firebase_ui_auth: ^1.14.0
  sign_in_with_apple: ^6.1.0
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.3
  http: ^1.2.2
  assistant_openai: ^1.0.4
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2
  uni_links: ^0.5.1
  just_audio: ^0.9.40
  audio_waveforms: ^1.0.5
  audio_session: ^0.1.18
  win32: ^5.5.0
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  build_web_compilers: ^4.0.10
  flutter_native_splash: ^2.4.0
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/ContextForModel.txt
    - assets/ContextForLoveSessionModel.txt
    - assets/history_chat.txt
    - assets/graphics/bg_forest.jpg
    - assets/graphics/logo_white.svg
    - assets/graphics/freepik--Leaves.svg
    - assets/graphics/onboarding_bg.svg
    - assets/graphics/onboarding_bg_bottom.svg
    - assets/graphics/birds_icon.png
    - assets/graphics/holding-hands_icon.png
    - assets/graphics/ideas_wiss_an_icon.png
    - assets/graphics/therapy-chat-icon.png
    - assets/graphics/daten-shield-icon.png
    - assets/graphics/love-session-forest-icon.png
    - assets/graphics/onboarding_leaves.svg
    - assets/graphics/apple_icon.png
    - assets/graphics/facebook_icon.png
    - assets/graphics/google_icon.png
    - assets/graphics/bez_prof_erstellen_icon.svg
    - assets/graphics/bez_prof_erstellen_icon.png
    - assets/graphics/leave_icon_blass.svg
    - assets/graphics/leave_icon.svg
    - assets/graphics/prof_erstellen_weiter_button.svg
    - assets/graphics/prof_erstellen_back_button.svg
    - assets/graphics/prof_erstellen_weiter_button.png
    - assets/graphics/männlich_icon.svg
    - assets/graphics/weiblich_icon.svg
    - assets/graphics/weiteres_icon.svg
    - assets/graphics/pic_upload_icon.svg
    - assets/graphics/profil_erstellen_MC_item_not_selected.svg
    - assets/graphics/profil_erstellen_MC_item_selected.svg
    - assets/graphics/send_message_icon.svg
    - assets/graphics/voice_input_icon.svg
    - assets/graphics/bell_icon.svg
    - assets/graphics/anonymus_icon.svg
    - assets/graphics/anonymus_icon_with_plus.svg
    - assets/graphics/E-mail_icon.svg
    - assets/graphics/whatsapp_icon.svg
    - assets/graphics/sms_icon.svg
    - assets/graphics/pop_up_X_button.svg
    - assets/graphics/home_love_session_starten_animation_graphic.svg
    - assets/graphics/home_screen_background_for_names_inkl_logo.svg
    - assets/graphics/home_screen_heart_dialoge.svg
    - assets/graphics/home_screen_love_session_starten_background_without_animation.svg
    - assets/graphics/home_screen_mint_star.svg
    - assets/graphics/home_screen_white_heart.svg
    - assets/graphics/home_screen_background_for_names_inkl_logo.png
    - assets/graphics/home_screen_love_session_starten_background_without_animation.png
    - assets/graphics/icon_menu_chat.svg
    - assets/graphics/icon_menu_home.svg
    - assets/graphics/icon_menu_inputs.svg
    - assets/graphics/icon_menu_love_session.svg
    - assets/graphics/icon_menu_sessions.svg
    - assets/graphics/logo_white_with_text.svg
    - assets/graphics/profile_screen_X_icon.svg
    - assets/graphics/profile_datenschutz_icon.svg
    - assets/graphics/profile_settings_icon.svg
    - assets/graphics/profile_star_icon.svg
    - assets/graphics/profile_ueberuns_icon.svg
    - assets/graphics/credit_card_icon.svg
    - assets/graphics/star_icon.svg
    - assets/graphics/bestaetigung_icon.svg
    - assets/graphics/logo_circle_icon.png
    - assets/graphics/trash_icon.svg
    - assets/graphics/therapeuten_chat_icon.svg
    - assets/graphics/logo_black.png
    

flutter_native_splash:
  color: "#414143"
  image: assets/graphics/logo_black.png
  android: true
  ios: true
  web: true
