// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAawdIn9yC-y4ZC8xjwK4r-3qrglbU1BBc',
    appId: '1:996434213634:web:9efe603baddb4da77fa01b',
    messagingSenderId: '996434213634',
    projectId: 'elovando-final',
    authDomain: 'elovando-final.firebaseapp.com',
    storageBucket: 'elovando-final.appspot.com',
    measurementId: 'G-GBEXJL034B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfDu9oW5h3Y43rZ0Dg3EpmEpzFgcu5y1g',
    appId: '1:996434213634:android:25a63ae80acc50de7fa01b',
    messagingSenderId: '996434213634',
    projectId: 'elovando-final',
    storageBucket: 'elovando-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8UHL3mEMj_wrPI7uuTz53DZ4ETQRfXCY',
    appId: '1:137798276523:ios:edacaa410f5ffa93be6eee',
    messagingSenderId: '137798276523',
    projectId: 'deescalateapp-12db3',
    storageBucket: 'deescalateapp-12db3.appspot.com',
    iosBundleId: 'com.example.newDeescalate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8UHL3mEMj_wrPI7uuTz53DZ4ETQRfXCY',
    appId: '1:137798276523:ios:938e6aae4373499abe6eee',
    messagingSenderId: '137798276523',
    projectId: 'deescalateapp-12db3',
    storageBucket: 'deescalateapp-12db3.appspot.com',
    iosBundleId: 'com.example.newDeescalate.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAawdIn9yC-y4ZC8xjwK4r-3qrglbU1BBc',
    appId: '1:996434213634:web:c58856388c40176e7fa01b',
    messagingSenderId: '996434213634',
    projectId: 'elovando-final',
    authDomain: 'elovando-final.firebaseapp.com',
    storageBucket: 'elovando-final.appspot.com',
    measurementId: 'G-7S8JP7WXR4',
  );

}