// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGuyVTz4vkasmiN8ahxBqbnydy4FX2Drc',
    appId: '1:137798276523:web:ca36d72c921c49cabe6eee',
    messagingSenderId: '137798276523',
    projectId: 'deescalateapp-12db3',
    authDomain: 'deescalateapp-12db3.firebaseapp.com',
    storageBucket: 'deescalateapp-12db3.appspot.com',
    measurementId: 'G-LG8NR0SQYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtX895NRQGl6vuaKqFjXiyRKCZaR7FpTc',
    appId: '1:137798276523:android:6c30a9aaa47703f1be6eee',
    messagingSenderId: '137798276523',
    projectId: 'deescalateapp-12db3',
    storageBucket: 'deescalateapp-12db3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8UHL3mEMj_wrPI7uuTz53DZ4ETQRfXCY',
    appId: '1:137798276523:ios:edacaa410f5ffa93be6eee',
    messagingSenderId: '137798276523',
    projectId: 'deescalateapp-12db3',
    storageBucket: 'deescalateapp-12db3.appspot.com',
    iosBundleId: 'com.example.newDeescalate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8UHL3mEMj_wrPI7uuTz53DZ4ETQRfXCY',
    appId: '1:137798276523:ios:938e6aae4373499abe6eee',
    messagingSenderId: '137798276523',
    projectId: 'deescalateapp-12db3',
    storageBucket: 'deescalateapp-12db3.appspot.com',
    iosBundleId: 'com.example.newDeescalate.RunnerTests',
  );
}
